# -*- coding: utf-8 -*-
"""game_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKibJYPAUGYU_nOfRA9chUyudpNruXCu
"""

import random

a,b=map(int,input("Input Upper limit and Lower limit").split())
num=random.randint(b,a)
c=int(input("press number of chances you need to guess correctly "))
flag=0
b1=b
a1=a

for i in range(c):

  h11=0
  h12=0
  h13=0
  h14=0
  d=int(input("you:"))
  ds=random.randint(b,a)
  print("she:",ds)
  if a1==b1:
    dh=a1
    print("he:",dh)
  else:
    dh=random.randint(b1,a1)
    print("he:",dh)
  if (d==num):
    print("You win")
    flag=1
    break;
  elif (d<num):
    print("you Guess bigger")
    h11=1
  elif (d>num):
    print("you guess smaller")
  if (ds==num):
    print("she wins")
    break;
  elif (ds<num):
    print("she Guessed bigger")
    h12=1
  elif (ds>num):
    print("she guessed smaller")

  if (dh==num):
    print("he wins")
    break;



  elif (dh<num):
    print("he Guess bigger")
    if h11==1 and h12==1:
      b1=max(d,ds)
      b1=max(b1,dh)
      b1+=1
    elif h11==1:
      b1=max(d,dh)
      b1+=1
      a1=min(a1,ds)
      a1-=1
    elif h12==1:
      b1=max(dh,ds)
      b1+=1
      a1=min(a1,d)
      a1-=1
    else:
      b1=dh+1
      a1=min(a1,d)
      a1=min(a1,ds)-1


  elif (dh>num):
    print("he guessed smaller")
    if h11==0 and h12==0:
      a1=min(d,ds)
      a1=min(a1,dh)
      a1-=1
    elif h11==0:
      a1=min(d,dh)
      a1-=1
      b1=max(b1,ds)
      b1+=1
    elif h12==0:
      a1=min(dh,ds)
      a1-=1
      b1=max(b1,d)
      b1+=1
    else:
      a1=dh-1
      b1=max(b1,d)
      b1=max(b1,ds)+1
  print((c-i-1),"chances left")



if flag==0:
  print("You lost")
  print("number is ",num)